#!/usr/bin/env python3
"""Build Desk/Lessons Digest.md: the Coach's experience, newest first, for every seat to read. Usage: build_lessons.py [max_chars]"""
import pathlib,re,sys
V=pathlib.Path(__file__).resolve().parents[1]; MAX=int(sys.argv[1]) if len(sys.argv)>1 else 12000
out=["---","type: digest","note: generated by Scripts/build_lessons.py — do not edit; edit Reviews/ and Lessons/ instead","---","# Lessons Digest (newest first)",""]
reviews=sorted((V/"Reviews").glob("*.md"), reverse=True)[:3] if (V/"Reviews").exists() else []
lessons=sorted((V/"Lessons").glob("*.md"), key=lambda p:p.stat().st_mtime, reverse=True) if (V/"Lessons").exists() else []
if not reviews and not lessons: out.append("_No reviews or lessons yet — the Coach writes the first after the first full session._")
for r in reviews:
    t=r.read_text(); body=re.sub(r"^---.*?---\s*","",t,flags=re.S)
    keep=[]; grab=False
    for line in body.splitlines():
        if re.match(r"^## (Seat grades|What worked|What failed|Lessons|Rule changes)",line): grab=True
        elif line.startswith("## "): grab=False
        if grab or line.startswith("# "): keep.append(line)
    out+=[f"## Review {r.stem}", *keep, ""]
for l in lessons:
    t=l.read_text(); body=re.sub(r"^---.*?---\s*","",t,flags=re.S).strip()
    out+=[f"## {l.stem}", body, ""]
txt="\n".join(out)
if len(txt)>MAX: txt=txt[:MAX]+"\n\n_(digest truncated at %d chars — older material omitted)_"%MAX
(V/"Desk"/"Lessons Digest.md").write_text(txt); print("wrote Desk/Lessons Digest.md", len(txt), "chars;", len(reviews), "reviews,", len(lessons), "lessons")
