#!/usr/bin/env python3
"""Build Desk/Lessons Digest.md (the Coach's experience, newest first, for every seat) and Desk/Expectancy.md (per-setup stats from the ledger).
Usage: build_lessons.py [max_chars]"""
import pathlib,re,sys,json,subprocess
V=pathlib.Path(__file__).resolve().parents[1]; MAX=int(sys.argv[1]) if len(sys.argv)>1 else 12000
# ---- expectancy table from the execution layer's ledger ----
exp_md=["---","type: expectancy","note: generated by Scripts/build_lessons.py from Journal/ledger.json via exec.py stats — do not edit","---","# Setup expectancy (paper ledger, all sessions)","",
        "Status rule: **sample** (<10 trades) → default size · **proven** (≥10, avg R ≥ 0.3) → may use the max risk number · **marginal** (≥10, 0 ≤ avg R < 0.3) → low-confidence size · **disabled** (≥10, avg R < 0) → no entries until the Coach reviews.",""]
try:
    st=json.loads(subprocess.run([sys.executable,"-I",str(V/"Scripts/broker/exec.py"),"stats"],capture_output=True,text=True,timeout=30).stdout)
    rows=st.get("setups",[])
    if rows:
        exp_md+=["| Setup | Trades | Win % | Avg R | P&L $ | Status |","|---|---|---|---|---|---|"]
        exp_md+=[f"| {r['setup']} | {r['n']} | {r['win_rate']} | {r['avg_r'] if r['avg_r'] is not None else '—'} | {r['sum_pnl']} | **{r['status']}** |" for r in rows]
        exp_md+=["","## Trades","","| Day | Ticker | Setup | Side | R | P&L $ |","|---|---|---|---|---|---|"]
        exp_md+=[f"| {t.get('day')} | {t['symbol']} | {t['setup']} | {t.get('side')} | {t.get('r') if t.get('r') is not None else '—'} | {round(t['pnl'],2)}{' (approx)' if t.get('approx') else ''} |" for t in st.get("trades",[])]
    else: exp_md.append("_No closed trades yet — every setup is a sample. The first rows appear after the first exit._")
except Exception as e: exp_md.append(f"_stats unavailable: {e}_")
(V/"Desk"/"Expectancy.md").write_text("\n".join(exp_md)+"\n")
# ---- digest ----
out=["---","type: digest","note: generated by Scripts/build_lessons.py — do not edit; edit Reviews/ and Lessons/ instead","---","# Lessons Digest (newest first)","",
     "## Setup expectancy (numbers beat prose — size by these)",*[l for l in exp_md[5:] if not l.startswith("## Trades")][:40],""]
reviews=sorted((V/"Reviews").glob("*.md"), reverse=True)[:3] if (V/"Reviews").exists() else []
lessons=sorted((V/"Lessons").glob("*.md"), key=lambda p:p.stat().st_mtime, reverse=True) if (V/"Lessons").exists() else []
if not reviews and not lessons: out.append("_No reviews or lessons yet — the Coach writes the first after the first full session._")
for r in reviews:
    t=r.read_text(); body=re.sub(r"^---.*?---\s*","",t,flags=re.S)
    keep=[]; grab=False
    for line in body.splitlines():
        if re.match(r"^## (Seat grades|What worked|What failed|Lessons|Rule changes|Pace vs targets)",line): grab=True
        elif line.startswith("## "): grab=False
        if grab or line.startswith("# "): keep.append(line)
    out+=[f"## Review {r.stem}", *keep, ""]
for l in lessons:
    t=l.read_text(); body=re.sub(r"^---.*?---\s*","",t,flags=re.S).strip()
    out+=[f"## {l.stem}", body, ""]
txt="\n".join(out)
if len(txt)>MAX: txt=txt[:MAX]+"\n\n_(digest truncated at %d chars — older material omitted)_"%MAX
(V/"Desk"/"Lessons Digest.md").write_text(txt); print("wrote Desk/Lessons Digest.md", len(txt), "chars;", len(reviews), "reviews,", len(lessons), "lessons; Desk/Expectancy.md", len(rows) if 'rows' in dir() else 0, "setups")
